// Auto-generated by scripts/gen-sw.mjs — do not edit.
const SHELL_CACHE = "colorize-shell-bfd12ddae50b"
const MODEL_CACHE = "colorize-model-v3"
const BASE = "/colorize/"
const PRECACHE = [
  "/colorize/",
  "/colorize/assets/index-DzrUxZ3E.css",
  "/colorize/assets/index.src-CFzVBlbo.js",
  "/colorize/favicon.svg",
  "/colorize/index.html",
  "/colorize/manifest.webmanifest",
  "/colorize/ort/ort-wasm-simd-threaded.jsep.mjs",
  "/colorize/ort/ort-wasm-simd-threaded.jsep.wasm"
]

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(SHELL_CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting())
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        // Drop old shell caches and any stale model bucket from a previous
        // model version; KEEP the current model cache (expensive to refetch).
        keys
          .filter(
            (k) =>
              (k.startsWith('colorize-shell-') && k !== SHELL_CACHE) ||
              (k.startsWith('colorize-model-') && k !== MODEL_CACHE)
          )
          .map((k) => caches.delete(k))
      )
    ).then(() => self.clients.claim())
  )
})

self.addEventListener('fetch', (event) => {
  const req = event.request
  if (req.method !== 'GET') return
  const url = new URL(req.url)

  // Model bucket: serve from the model cache if present (works offline),
  // otherwise hit the network (first download path in modelStore.js).
  if (url.pathname.includes('/models/')) {
    event.respondWith(
      caches.open(MODEL_CACHE).then((c) =>
        c.match(req).then((hit) => hit || fetch(req))
      )
    )
    return
  }

  // App shell: cache-first. SPA navigations fall back to the cached index.
  event.respondWith(
    caches.match(req).then((hit) => {
      if (hit) return hit
      return fetch(req).catch(() => {
        if (req.mode === 'navigate') return caches.match(BASE)
        return Response.error()
      })
    })
  )
})
