// Post-build: generate dist/sw.js with a precache manifest of the app shell.
//
// Two-tier offline strategy:
//   TIER 1 (this file): app shell — index.html, hashed JS/CSS, manifest, icons,
//           ab_bins.json, and the ORT WASM/mjs. Precached on install, served
//           cache-first. Versioned by a content hash so deploys update cleanly.
//   TIER 2 (modelStore.js): the ~123MB model in its own Cache Storage bucket,
//           fetched on first use. The SW NEVER precaches it (excluded below),
//           but DOES serve it from that bucket when the network is offline.

import { createHash } from 'node:crypto'
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dist = join(root, 'dist')
const BASE = '/colorize/'
const MODEL_CACHE = 'colorize-model-v2' // keep in sync with src/config.js

// Walk dist/, collecting shell files. Exclude the model and the SW itself.
function walk(dir, acc = []) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name)
    const st = statSync(full)
    if (st.isDirectory()) {
      walk(full, acc)
    } else {
      acc.push(full)
    }
  }
  return acc
}

// Exclude: the model bucket; the SW + sourcemaps; and the hashed WASM that Vite
// emits into assets/ — it's a dead duplicate since ORT's wasmPaths points at the
// self-hosted /ort/ copy, so precaching it would waste ~21MB.
const EXCLUDE = [/\/models\//, /sw\.js$/, /\.map$/, /\/assets\/ort-wasm.*\.wasm$/]
const files = walk(dist).filter((f) => !EXCLUDE.some((re) => re.test(f)))

// URLs to precache (relative to the Pages base path). The deploy step renames
// index.src.html -> index.html at the root, so normalize that here too.
const urls = files
  .map((f) => BASE + relative(dist, f).split('\\').join('/'))
  .map((u) => u.replace(/index\.src\.html$/, 'index.html'))
  .sort()
// Ensure the app entry resolves offline at the base URL too.
if (!urls.includes(BASE)) urls.unshift(BASE)

// Version = hash of all shell file contents, so the cache busts on any change.
const hash = createHash('sha256')
for (const f of files.sort()) hash.update(readFileSync(f))
const VERSION = hash.digest('hex').slice(0, 12)
const SHELL_CACHE = `colorize-shell-${VERSION}`

const sw = `// Auto-generated by scripts/gen-sw.mjs — do not edit.
const SHELL_CACHE = ${JSON.stringify(SHELL_CACHE)}
const MODEL_CACHE = ${JSON.stringify(MODEL_CACHE)}
const BASE = ${JSON.stringify(BASE)}
const PRECACHE = ${JSON.stringify(urls, null, 2)}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(SHELL_CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting())
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        // Drop old shell caches and any stale model bucket from a previous
        // model version; KEEP the current model cache (expensive to refetch).
        keys
          .filter(
            (k) =>
              (k.startsWith('colorize-shell-') && k !== SHELL_CACHE) ||
              (k.startsWith('colorize-model-') && k !== MODEL_CACHE)
          )
          .map((k) => caches.delete(k))
      )
    ).then(() => self.clients.claim())
  )
})

self.addEventListener('fetch', (event) => {
  const req = event.request
  if (req.method !== 'GET') return
  const url = new URL(req.url)

  // Model bucket: serve from the model cache if present (works offline),
  // otherwise hit the network (first download path in modelStore.js).
  if (url.pathname.includes('/models/')) {
    event.respondWith(
      caches.open(MODEL_CACHE).then((c) =>
        c.match(req).then((hit) => hit || fetch(req))
      )
    )
    return
  }

  // App shell: cache-first. SPA navigations fall back to the cached index.
  event.respondWith(
    caches.match(req).then((hit) => {
      if (hit) return hit
      return fetch(req).catch(() => {
        if (req.mode === 'navigate') return caches.match(BASE)
        return Response.error()
      })
    })
  )
})
`

writeFileSync(join(dist, 'sw.js'), sw)
console.log(`gen-sw: wrote dist/sw.js (${SHELL_CACHE}, ${urls.length} shell files)`)
